### ISSUE TITLE
Suggest the 1.x version support both php 7 & 8

### ISSUE THREAD

**Issue by iLexN** [sebastiansulinski/smart-quotes#3]
Thanks for your work.

In my project is using php 7.4, and going to upgrade to use php 8.0.

It is hard for me to upgrade the whole project to 8.0 in the same time. 

I suggest to 1.x version support both php 7 & 8 for more easy upgrade path.

if you ok with this, i will prepare the change.

Thanks.

**Comment by sebastiansulinski** [comment]
Thank you @iLexN - I will be upgrading this package soon to support v8 + of PHP so no need for the PR as it is already on my todo list.

**Comment by iLexN** [comment]
now v1.3 is support php 7, and v2 is support php 8.

in my case, if there have a v1.4 support both php 7 and 8 will be great.

**Comment by sebastiansulinski** [comment]
@iLexN that's now been updated in the latest release v2.0.1

**Comment by iLexN** [comment]
thank a lot
